name: CI

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

permissions:
  contents: read

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3.4.0
        with:
          submodules: recursive

      - name: Prepare build environemnt
        id: prepare
        uses: ./.github/actions/prepare-build-env

      - name: Run cargo clippy
        run: |
          cargo clippy --tests -- --deny "warnings"

      - name: Post build environemnt
        if: always()
        uses: ./.github/actions/post-build-env
        with:
          cargo-cache-primary-key: ${{ steps.prepare.outputs.cargo-cache-primary-key }}
          cargo-cache-hit: ${{ steps.prepare.outputs.cargo-cache-hit }}

  build:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3.4.0
        with:
          submodules: recursive

      - name: Prepare build environemnt
        id: prepare
        uses: ./.github/actions/prepare-build-env

      - name: Run cargo build
        run: cargo build

      - name: Post build environemnt
        if: always()
        uses: ./.github/actions/post-build-env
        with:
          cargo-cache-primary-key: ${{ steps.prepare.outputs.cargo-cache-primary-key }}
          cargo-cache-hit: ${{ steps.prepare.outputs.cargo-cache-hit }}

  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3.4.0
        with:
          submodules: recursive

      - name: Prepare build environemnt
        id: prepare
        uses: ./.github/actions/prepare-build-env

      - name: Use libegl1-mesa latest
        uses: ./.github/actions/install-graphics-driver

      - name: Run cargo test
        run: |
          cargo test -- --nocapture

      - name: Post build environemnt
        if: always()
        uses: ./.github/actions/post-build-env
        with:
          cargo-cache-primary-key: ${{ steps.prepare.outputs.cargo-cache-primary-key }}
          cargo-cache-hit: ${{ steps.prepare.outputs.cargo-cache-hit }}